# Generated by Django 3.0.7 on 2020-07-13 22:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0002_visitevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionrule',
            name='max_id_distance',
            field=models.IntegerField(default=150, verbose_name='Максимальное расстояние для соотнесения потеренного идентификатора'),
        ),
        migrations.AddField(
            model_name='detectionrule',
            name='max_id_live',
            field=models.IntegerField(default=50, verbose_name='Жизнь идентификатора после потери (кадров)'),
        ),
        migrations.AlterField(
            model_name='rateval',
            name='allowed_classes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('boat', 'Плавательные суда'), ('person', 'Люди')], max_length=200, verbose_name='Классы объектов которым можно находиться в зоне'),
        ),
    ]
