# Generated by Django 3.0.7 on 2020-07-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0004_auto_20200721_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitevent',
            name='distance_to_cam',
            field=models.FloatField(blank=True, null=True, verbose_name='Расстояние до камеры'),
        ),
    ]
