# Generated by Django 3.0.7 on 2020-07-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0006_auto_20200723_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateval',
            name='event_type',
            field=models.IntegerField(choices=[(6, 'Береговая охрана: нарушение безопасной зоны'), (61, 'Береговая охрана: нарушение безопасной зоны (ночь)'), (7, 'Береговая охрана: фиксация объекта'), (8, 'Береговая охрана: столкновение (опасное сближение)'), (9, 'Береговая охрана: утопление (исчезновения человека в воде)')], default=7, verbose_name='Тип события'),
        ),
        migrations.RemoveField(
            model_name='rateval',
            name='allowed_classes',
        ),
        migrations.AddField(
            model_name='rateval',
            name='allowed_classes',
            field=models.ManyToManyField(to='object_detection.DetectionRule', verbose_name='Классы объектов которым можно находиться в зоне'),
        ),
    ]
