# Generated by Django 3.0.7 on 2020-07-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0009_auto_20200728_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateval',
            name='allowed_classes',
            field=models.ManyToManyField(blank=True, to='object_detection.DetectionRule', verbose_name='Классы объектов которым можно находиться в зоне'),
        ),
    ]
