# Generated by Django 3.0.7 on 2020-08-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0010_auto_20200728_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='raterule',
            name='is_group_rule',
            field=models.BooleanField(default=False, verbose_name='Проверка для группы объектов'),
        ),
        migrations.AlterField(
            model_name='raterule',
            name='event_type',
            field=models.IntegerField(choices=[(-1, 'ТЕХНОЛОГИЧЕСКОЕ СООБЩЕНИЕ'), (6, 'Береговая охрана: нарушение безопасной зоны'), (61, 'Береговая охрана: нарушение безопасной зоны (ночь)'), (7, 'Береговая охрана: фиксация объекта'), (8, 'Береговая охрана: столкновение (опасное сближение)'), (9, 'Береговая охрана: утопление (исчезновения человека в воде)')], default=7, verbose_name='Тип диагностируемого события'),
        ),
        migrations.AlterField(
            model_name='rateval',
            name='max_val',
            field=models.FloatField(help_text='Для временных характеристик задаются часы дня по гринвичу', verbose_name='Максимальное начение проверяемого параметра'),
        ),
        migrations.AlterField(
            model_name='rateval',
            name='min_val',
            field=models.FloatField(help_text='Для временных характеристик задаются часы дня по гринвичу', verbose_name='Минимальное значение проверяемого параметра'),
        ),
        migrations.AlterField(
            model_name='visitevent',
            name='event_type',
            field=models.IntegerField(choices=[(-1, 'ТЕХНОЛОГИЧЕСКОЕ СООБЩЕНИЕ'), (6, 'Береговая охрана: нарушение безопасной зоны'), (61, 'Береговая охрана: нарушение безопасной зоны (ночь)'), (7, 'Береговая охрана: фиксация объекта'), (8, 'Береговая охрана: столкновение (опасное сближение)'), (9, 'Береговая охрана: утопление (исчезновения человека в воде)')], default=7, verbose_name='Тип события'),
        ),
    ]
