# Generated by Django 3.0.7 on 2020-08-04 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0011_auto_20200801_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='markpoint',
            name='point_type',
            field=models.IntegerField(choices=[(0, 'Точка гео-разметки'), (1, 'Точка разметки зон')], default=0, verbose_name='Тип разметки'),
        ),
        migrations.AddField(
            model_name='rateval',
            name='multi_points',
            field=models.ManyToManyField(null=True, to='object_detection.MarkPoint', verbose_name='Точки не прямоугольной разметки'),
        ),
        migrations.AlterField(
            model_name='markpoint',
            name='order_num',
            field=models.IntegerField(help_text='Нумерация внутри типа разметки', verbose_name='Порядковый номер точки (по часовой стрелке с левой верхней)'),
        ),
        migrations.AlterField(
            model_name='markpoint',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object_detection.SensorData', verbose_name='Точки для разметки дальности'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='aktive_rate_rules',
            field=models.ManyToManyField(blank=True, to='object_detection.RateRule', verbose_name='Активные правила оценки'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='obj_detection_rules',
            field=models.ManyToManyField(blank=True, to='object_detection.DetectionRule', verbose_name='Разпознаваемые классы'),
        ),
    ]
