# Generated by Django 3.0.7 on 2020-08-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0013_auto_20200804_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitevent',
            name='obj_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип объекта'),
        ),
        migrations.AddField(
            model_name='visitevent',
            name='zone_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Зона мониторинга'),
        ),
    ]
